-- Users Profile Table
create table public.profiles (
  id uuid references auth.users not null primary key,
  username text,
  avatar_url text,
  updated_at timestamp with time zone
);

-- User Playlists Table
create table public.user_playlists (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  name text not null,
  image text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Playlist Songs Junction Table (storing JSON to preserve original song data structure)
create table public.playlist_songs (
  id bigint generated by default as identity primary key,
  playlist_id bigint references public.user_playlists on delete cascade not null,
  song_data jsonb not null,
  added_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Liked Songs Table
create table public.liked_songs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  song_data jsonb not null,
  liked_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Row Level Security (RLS)
alter table profiles enable row level security;
alter table user_playlists enable row level security;
alter table playlist_songs enable row level security;
alter table liked_songs enable row level security;

-- Policies
create policy "Public profiles are viewable by everyone." on profiles for select using ( true );
create policy "Users can insert their own profile." on profiles for insert with check ( auth.uid() = id );
create policy "Users can update own profile." on profiles for update using ( auth.uid() = id );

create policy "Users can view own playlists." on user_playlists for select using ( auth.uid() = user_id );
create policy "Users can insert own playlists." on user_playlists for insert with check ( auth.uid() = user_id );
create policy "Users can delete own playlists." on user_playlists for delete using ( auth.uid() = user_id );

create policy "Users can view songs in own playlists." on playlist_songs for select using (
  exists ( select 1 from user_playlists where id = playlist_songs.playlist_id and user_id = auth.uid() )
);
create policy "Users can add songs to own playlists." on playlist_songs for insert with check (
  exists ( select 1 from user_playlists where id = playlist_songs.playlist_id and user_id = auth.uid() )
);

create policy "Users can view own liked songs." on liked_songs for select using ( auth.uid() = user_id );
create policy "Users can insert own liked songs." on liked_songs for insert with check ( auth.uid() = user_id );
create policy "Users can delete own liked songs." on liked_songs for delete using ( auth.uid() = user_id );
